### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by laraujo7** [cesium/CeSIUMpeloMundo#59]
Whenever you guys have time for this :muscle: 

![2022-09-13-150847_702x164_scrot](https://user-images.githubusercontent.com/44007026/189924093-d180c4ad-82e9-47b9-91d1-9181576175f0.png)

**Comment by sassypocoyo** [comment]
Good point, thanks! Will look into it :)

**Comment by joaodiaslobo** [comment]
This has been resolved.
